name: vikunja_widgetbook
description: Component workshop for the Vikunja app UI library.
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  vikunja_app:
    path: ../
  widgetbook: ^3.14.0

dev_dependencies:
  flutter_lints: ^6.0.0
